version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: payment-postgres

    environment:
      POSTGRES_DB: Paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ajay@2005

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-service:
    build: .

    container_name: payment-service

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Paymentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ajay@2005

    depends_on:
      - postgres

volumes:
  postgres_data: