spring.application.name=payment-service

stripe.secret-key=YOUR_STRIPE_SECRET_KEY

spring.datasource.url=jdbc:postgresql://localhost:5433/Paymentdb
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.api-key=my-secret-payment-key

jwt.secret=YOUR_JWT_SECRET
jwt.expiration=86400000

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=Payment Service
info.app.version=1.0
info.app.description=Stripe Payment Microservice

stripe.webhook.secret=YOUR_WEBHOOK_SECRET